root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  previous/page: new-folder/page.md

pdf:
  fontSize: 12
  paperSize: a4
  chapterMark: pagebreak
  pageBreaksBefore: /
  margin:
    right: 62
    left: 62
    top: 56
    bottom: 56